#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1";  IMAGE="$2"

# detect bower file, in case it exists run bower install
ret=$(docker run -i $IMAGE /bin/bash -c  "if [[ -f /app/bower.json ]]; then echo 'bower'; fi")
if [[  "$ret" == "bower" ]]; then
	id=$(docker run -i $IMAGE /bin/bash -c "cd /app && bower install")
	test $(docker wait $id) -eq 0
	docker commit $id $IMAGE > /dev/null
fi

