#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1";  IMAGE="dokku/$APP"

BOWERSCRIPT="
#!/bin/bash

cd /app
PATH=\$PATH:/app/vendor/node/bin
if [[ -f ./bower.json ]]; then
	npm install -g bower && bower install --allow-root
fi
"

echo '-----> Injecting bower script'
id=$(echo "$BOWERSCRIPT" | docker run -i -a stdin $IMAGE /bin/bash -c "cat > /app/.bower")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
id=$(docker run -d $IMAGE /bin/bash -c "chmod +x /app/.bower")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
