#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1";  IMAGE="$2"

BOWERINSTALL=$(cat <<EOF
PATH=$PATH:/app/vendor/node/bin &&
cd /app &&
npm install bower
EOF
)

PACKAGESINSTALL=$(cat <<EOF
PATH=$PATH:/app/vendor/node/bin &&
cd /app &&
./node_modules/bower/bin/bower install
EOF
)

echo '-----> Installing bower'
id=$(docker run -d $IMAGE /bin/bash -c "$BOWERINSTALL")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
echo '-----> Installing bower packages'
id=$(docker run -d $IMAGE /bin/bash -c "$PACKAGESINSTALL")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
