#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1";  IMAGE="dokku/$APP"

echo '-----> Running bower script'
id=$(docker run -d $IMAGE /bin/bash -c "/app/.bower")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
